version: '3.8'

services:
  service_monitor:
    build: .
    image: service_monitor:latest
    container_name: docker_service_monitor
    restart: always
    ports:
      - "1280:3000"
    environment:
      PORT: 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
